### PR TITLE
kodi: disable opengles shaders bt.709 color conversion for software d…

### PR DESCRIPTION
**Pull request by ilmich**
…ecoder

### CODE REVIEW

**Comment by knaerzche** [comment]
Thanks @ilmich for you contribution :) Would you mind packing this under `projects/Rockchip/devices/RK322x/patches/kodi`? It will then only be included when building for RK322x - the other targets might not need it.  I guess there is a typo in filename, I think you wanted to call it kodi-100.26-shaders-disable-bt709-color-conver**s**ion.patch

**Comment by ilmich** [comment]
Hi @knaerzche, check if now it's ok :)
Thanks to you because with your hard work you have made my box useful again ;)

**Comment by knaerzche** [comment]
allmost done: its now in projects/Rockchip - I'd like to have it in projects/Rockchip/devices/RK322x ... its mainly because I don't wanna run in too much trouble when merging changes from upstream LE

**Comment by ilmich** [comment]
Sorry, I misunderstood :(. Now it should be ok.

**Comment by knaerzche** [comment]
Thx again :)

**Pull request merged**
